const $=id=>document.getElementById(id);
const S=JSON.parse(localStorage.getItem("mt_scores")||"{}");
const sv=()=>{try{localStorage.setItem("mt_scores",JSON.stringify(S))}catch(e){}};
const TABS=[["home","🏠 Beranda"],["chap","📘 Bagan"],["calc","🧮 Kalkulator"],["glos","📖 Glosarium"],["rekap","📊 Rekap Skor"]];
let cur=0,stp=0,ans={};
const NB=t=>`<button data-t="${t[0]}">${t[1]}</button>`;$("nav").innerHTML=`<div class="nl mono">BELAJAR</div>${TABS.slice(0,2).map(NB).join("")}<div class="nl mono">FITUR &amp; ALAT BANTU</div>${TABS.slice(2).map(NB).join("")}`;
const tg=o=>{$("nav").classList.toggle("open",o);$("ov").classList.toggle("on",o)};$("mb").onclick=()=>tg(!$("nav").classList.contains("open"));$("ov").onclick=()=>tg(false);
$("nav").onclick=e=>{if(e.target.dataset.t)go(e.target.dataset.t)};
function go(t){tg(false);document.querySelectorAll(".pn").forEach(p=>p.classList.toggle("on",p.id==t));document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("on",b.dataset.t==t));if(t=="rekap")rk();if(t=="chap")ch();window.scrollTo(0,0)}
function home(){$("home").innerHTML=`<div class="card"><h3>Selamat datang di Master Turning</h3>Pelajari 6 jenis pembubutan: materi → video → tes 15 soal. Gunakan kalkulator parameter, glosarium, dan pantau rekap skor.</div><div class="grid">${C.map((c,i)=>`<div class="card ch" onclick="cur=${i};stp=0;go('chap')"><b>0${i+1}</b><h3>${c.t}</h3><span class="tag">${c.s}</span><div class="mono" style="margin-top:6px">Skor: ${S[i]?S[i].best:"–"}/15</div></div>`).join("")}</div>`}
function ch(){const c=C[cur];let h=`<div class="steps mono">${C.map((x,i)=>`<button class="${i==cur?"on":""}" onclick="cur=${i};stp=0;ch()">${i+1}</button>`).join("")}</div><h2 class="mono">Bagan ${cur+1}: ${c.t}</h2><div class="steps"><button class="${stp==0?"on":""}" onclick="stp=0;ch()">1 Materi</button><button class="${stp==1?"on":""}" onclick="stp=1;ch()">2 Video</button><button class="${stp==2?"on":""}" onclick="stp=2;ch()">3 Tes</button></div>`;
if(stp==0)h+=`<div class="card mat"><h3>${c.s}</h3><ul>${c.m.map(x=>`<li>${x}</li>`).join("")}</ul></div>`;
if(stp==1){const v=VID[cur];h+=`<div class="vid">${v?`<iframe src="https://www.youtube-nocookie.com/embed/${v}" allowfullscreen></iframe>`:`<div>Video bagan ini belum dipasang.<br><a target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=${encodeURIComponent("proses bubut "+c.t+" mesin bubut")}">Cari video di YouTube ↗</a></div>`}</div>`}
if(stp==2){h+=`<div class="card"><h3>Tes Bagan ${cur+1} · 15 Soal</h3>Pilih satu jawaban, lalu tekan Kirim.</div><div id="qs"></div><button class="btn" onclick="sub()">KIRIM JAWABAN</button><div id="sc"></div>`}
$("chap").innerHTML=h;if(stp==2)qs()}
function qs(){const L=C[cur].q.split("\n").map(l=>l.split("|"));ans={};$("qs").innerHTML=L.map((r,i)=>{const o=r.slice(1).map((t,j)=>({t,c:!j}));o.sort(()=>Math.random()-.5);ans[i]=o;return`<div class="q" id="q${i}"><b>${i+1}. ${r[0]}</b>${o.map((x,j)=>`<label class="${x.c?"c":""}"><span class="lt">${"ABCD"[j]}</span><span class="tx">${x.t}</span><input type="radio" name="r${i}" value="${j}"></label>`).join("")}</div>`}).join("")}
function sub(){let s=0;for(let i=0;i<15;i++){const p=document.querySelector(`input[name=r${i}]:checked`);const q=$("q"+i);q.classList.add("r");if(p&&ans[i][p.value].c)s++;else if(p)p.parentElement.classList.add("w")}
const o=S[cur]||{best:0,n:0};S[cur]={best:Math.max(o.best,s),last:s,n:o.n+1};sv();$("sc").innerHTML=`<div class="card"><div class="big">${s}/15</div>Nilai: ${Math.round(s/15*100)} · ${s>=11?"Tuntas ✅":"Belum tuntas, pelajari materi lalu coba lagi"}</div>`;$("sc").scrollIntoView()}
function calc(){$("calc").innerHTML=`<div class="card"><h3>Kalkulator Parameter Bubut</h3><div class="f"><div>Diameter d (mm)<input id="d" type="number" value="40"></div><div>Vc (m/menit)<input id="vc" type="number" value="25"></div><div>Feed f (mm/put)<input id="fd" type="number" value="0.2" step="0.05"></div><div>Panjang L (mm)<input id="l" type="number" value="50"></div><div>Kedalaman a (mm)<input id="a" type="number" value="1"></div></div><div class="res"><div>n<b id="n">-</b>rpm</div><div>Vf<b id="vf">-</b>mm/menit</div><div>Waktu t<b id="t">-</b>menit</div><div>d akhir<b id="da">-</b>mm</div></div></div><div class="card"><h3>Kalkulator Tirus</h3><div class="f"><div>D besar (mm)<input id="D" type="number" value="30"></div><div>d kecil (mm)<input id="dk" type="number" value="20"></div><div>l tirus (mm)<input id="lt" type="number" value="50"></div><div>L total (mm)<input id="Lt" type="number" value="100"></div></div><div class="res"><div>Sudut α<b id="al">-</b>derajat</div><div>Rasio C<b id="cr">-</b></div><div>Geser tailstock S<b id="sg">-</b>mm</div></div></div><p class="mono" style="color:var(--mu)">n = 1000·Vc/(π·d) · Vf = f·n · t = L/Vf · tan α = (D−d)/(2·l)</p>`;
const g=i=>parseFloat($(i).value)||0,f=x=>isFinite(x)?x.toFixed(2):"-";
const u=()=>{const n=1000*g("vc")/(Math.PI*g("d")),vf=g("fd")*n;$("n").textContent=f(n);$("vf").textContent=f(vf);$("t").textContent=f(g("l")/vf);$("da").textContent=f(g("d")-2*g("a"));const D=g("D"),k=g("dk"),l=g("lt");$("al").textContent=f(Math.atan((D-k)/(2*l))*180/Math.PI);$("cr").textContent="1:"+f(l/(D-k));$("sg").textContent=f(g("Lt")*(D-k)/(2*l))};
$("calc").oninput=u;u()}
function glos(){$("glos").innerHTML=`<input id="gs" placeholder="Cari istilah…"><div id="gl"></div>`;const r=()=>{const q=$("gs").value.toLowerCase();$("gl").innerHTML=G.filter(x=>(x[0]+x[1]).toLowerCase().includes(q)).map(x=>`<div class="card"><h3>${x[0]}</h3>${x[1]}</div>`).join("")};$("gs").oninput=r;r()}
function rk(){const done=Object.keys(S).length;const avg=done?Math.round(Object.values(S).reduce((a,b)=>a+b.best,0)/done/15*100):0;$("rekap").innerHTML=`<div class="card"><h3>Ringkasan</h3>Bagan dikerjakan: <b>${done}/6</b> · Rata-rata nilai terbaik: <b class="big">${avg}</b><div class="bar"><i style="width:${done/6*100}%"></i></div></div><table><tr><th>Bagan</th><th>Terbaik</th><th>Terakhir</th><th>Percobaan</th><th>Status</th></tr>${C.map((c,i)=>{const s=S[i];return`<tr><td>${i+1}. ${c.t}</td><td>${s?s.best+"/15":"–"}</td><td>${s?s.last+"/15":"–"}</td><td>${s?s.n:0}</td><td>${s?(s.best>=11?"Tuntas ✅":"Remedial"):"Belum"}</td></tr>`}).join("")}</table><p><button class="btn" onclick="if(confirm('Hapus semua skor?')){for(const k in S)delete S[k];sv();rk();home()}">RESET SKOR</button></p>`}
home();calc();glos();go("home");
